name: Build Releases

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger for testing

env:
  BUILD_TYPE: Release
  QT_VERSION: '6.8.2'
  APP_ID: 'org.unabara.unabara'

jobs:
  build-linux-flatpak:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder elfutils
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.kde.Sdk//6.8
        sudo flatpak install -y org.kde.Platform//6.8
    
    - name: Set up Flatpak manifest
      run: |
        cat > org.unabara.unabara.yml << EOF
        app-id: ${{ env.APP_ID }}
        runtime: org.kde.Platform
        runtime-version: '6.8'
        sdk: org.kde.Sdk
        command: unabara
        finish-args:
          - --share=ipc
          - --socket=x11
          - --socket=wayland
          - --filesystem=host
          - --device=dri
        modules:
          - name: unabara
            buildsystem: cmake-ninja
            config-opts:
              - -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
            sources:
              - type: dir
                path: .
        EOF
    
    - name: Build Flatpak
      run: |
        flatpak-builder --repo=repo --force-clean build-dir org.unabara.unabara.yml
        flatpak build-bundle repo ${{ env.APP_ID }}.flatpak ${{ env.APP_ID }}
    
    - name: Upload Linux Flatpak Artifact
      uses: actions/upload-artifact@v4
      with:
        name: unabara-linux-flatpak
        path: ${{ env.APP_ID }}.flatpak
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.APP_ID }}.flatpak
        asset_name: unabara-linux.flatpak
        tag: ${{ github.ref }}
        overwrite: true

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        aqtversion: '==3.1.*'
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtmultimedia qtpositioning qtwebview'
 
    - name: Install MSBuild
      run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.Component.MSBuild"

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '14.36'
        msbuild-architecture: x64
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose
      
    - name: Package with windeployqt
      working-directory: ${{github.workspace}}/build
      run: |
        mkdir package
        if (Test-Path bin\${{env.BUILD_TYPE}}\unabara.exe) {
          copy bin\${{env.BUILD_TYPE}}\unabara.exe package\
        } elseif (Test-Path bin\unabara.exe) {
          copy bin\unabara.exe package\
        } else {
          Get-ChildItem -Recurse bin
          throw "Could not find unabara.exe in expected locations"
        }
        cd package
        $env:PATH = "$env:Qt6_DIR\bin;$env:PATH"
        windeployqt unabara.exe --release --no-translations --qmldir=../../src/ui/qml
        cd ..
        mv package ${{github.workspace}}/build/unabara-windows

    # - name: Create ZIP Archive (Direct)
    #   working-directory: ${{github.workspace}}/build
    #   run: |
    #     cd package
    #     7z a -tzip ${{github.workspace}}/build/unabara-windows.zip *

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: unabara-windows
        path: ${{github.workspace}}/build/unabara-windows
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/build/unabara-windows
        tag: ${{ github.ref }}
        overwrite: true

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        aqtversion: '==3.1.*'
        version: ${{ env.QT_VERSION }}
        host: mac
        target: desktop
        arch: clang_64
    
    - name: Configure CMake for Intel Build
      run: cmake -B ${{github.workspace}}/build-x86_64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES=x86_64
      
    - name: Build Intel Version
      run: cmake --build ${{github.workspace}}/build-x86_64 --config ${{env.BUILD_TYPE}}
    
    - name: Configure CMake for ARM Build
      run: cmake -B ${{github.workspace}}/build-arm64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES=arm64
      
    - name: Build ARM Version
      run: cmake --build ${{github.workspace}}/build-arm64 --config ${{env.BUILD_TYPE}}
    
    - name: Create Universal Binary
      run: |
        mkdir -p ${{github.workspace}}/build-universal/bin
        lipo -create \
          ${{github.workspace}}/build-x86_64/bin/unabara \
          ${{github.workspace}}/build-arm64/bin/unabara \
          -output ${{github.workspace}}/build-universal/bin/unabara
        chmod +x ${{github.workspace}}/build-universal/bin/unabara
        
    - name: Package Universal App
      working-directory: ${{github.workspace}}/build-universal
      run: |
        mkdir -p package/Unabara.app/Contents/MacOS/
        cp bin/unabara package/Unabara.app/Contents/MacOS/
        
        # Create Info.plist
        mkdir -p package/Unabara.app/Contents/
        cat > package/Unabara.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleExecutable</key>
          <string>unabara</string>
          <key>CFBundleIconFile</key>
          <string>unabara.icns</string>
          <key>CFBundleIdentifier</key>
          <string>org.unabara.unabara</string>
          <key>CFBundleName</key>
          <string>Unabara</string>
          <key>CFBundleDisplayName</key>
          <string>Unabara</string>
          <key>CFBundlePackageType</key>
          <string>APPL</string>
          <key>CFBundleSignature</key>
          <string></string>
          <key>CFBundleShortVersionString</key>
          <string>1.0</string>
          <key>CFBundleVersion</key>
          <string>1</string>
          <key>LSMinimumSystemVersion</key>
          <string>10.14</string>
          <key>NSPrincipalClass</key>
          <string>NSApplication</string>
          <key>NSHighResolutionCapable</key>
          <true/>
          <key>LSArchitecturePriority</key>
          <array>
            <string>arm64</string>
            <string>x86_64</string>
          </array>
        </dict>
        </plist>
        EOF
        
        # Deploy Qt dependencies
        macdeployqt package/Unabara.app -dmg -verbose=3
        mv package/Unabara.dmg unabara-macos-universal.dmg
        
    - name: Upload macOS Universal Artifact
      uses: actions/upload-artifact@v4
      with:
        name: unabara-macos-universal
        path: ${{github.workspace}}/build-universal/unabara-macos-universal.dmg
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/build-universal/unabara-macos-universal.dmg
        asset_name: unabara-macos-universal.dmg
        tag: ${{ github.ref }}
        overwrite: true
